# Setup
title:               O.W.L
tagline:             'Wireless Reading Group'
description:         'A magical world with advanced wireless technologies'
url:                 'https://owlreading.github.io/'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Akshay Gadre
  url:               https://www.akshaygadre.com/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
